FROM --platform=linux/amd64 nginx:latest
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./index_nginx.html /usr/share/nginx/html/main/index.html
COPY ./index_nginx.html /usr/share/nginx/html/index.html