apiVersion: v1
kind: Pod
metadata:
  name: nginx-web
  labels:
    app: nginx-web
spec:
  containers:
    - name: nginx-web
      image: docker.io/duq3r/nginx-main
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx-web
  ports:
    - port: 80
      targetPort: 80
  #type: LoadBalancer


# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-svc
# spec:
#   type: ExternalName
#   externalName: test-ssi.website.yandexcloud.net

      