apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Hello</h1>
    </br>
    <h1>This is index file from configmap. </h1>
    </html