apiVersion: v1
kind: Pod
metadata:
  name: header-web
  labels:
    app: header-web
spec:
  containers:
    - name: header-web
      image: docker.io/duq3r/header
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: header-svc
spec:
  selector:
    app: header-web
  ports:
    - port: 8080
      targetPort: 80