---
apiVersion: v1
kind: Pod
metadata:
  name: netology
spec:
  containers:
    - name: netology
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      ports:
      - containerPort: 8080
      