apiVersion: v1
kind: Pod
metadata:
  name: main-web
  labels:
    app: main-web
spec:
  containers:
    - name: main-web
      image: docker.io/duq3r/main
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: main-svc
spec:
  selector:
    app: main-web
  ports:
    - port: 8080
      targetPort: 80