apiVersion: v1
kind: Pod
metadata:
  name: footer-web
  labels:
    app: footer-web
spec:
  containers:
    - name: footer-web
      image: docker.io/duq3r/footer
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: footer-svc
spec:
  selector:
    app: footer-web
  ports:
    - port: 8080
      targetPort: 80


      