kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: [“group1”] # “” indicates the core API group
  resources: [“pods”]
  verbs: [“get”, “watch”, “list”]